export const RECIPE_LOAD = 'RECIPE_LOAD'
export const RECIPE_SUCCESS = 'RECIPE_SUCCESS'
export const RECIPE_FAILURE = 'RECIPE_FAILURE'

export const WEATHER_LOAD = 'WEATHER_LOAD'
export const WEATHER_SUCCESS = 'WEATHER_SUCCESS'
export const WEATHER_FAILURE = 'WEATHER_FAILURE'


export const LOAD_MAP_CORDINATES = 'LOAD_MAP_CORDINATES'
export const MAP_CORDINATES_SUCCESS = 'MAP_CORDINATES_SUCCESS'
export const MAP_CORDINATES_FAILURE = 'MAP_CORDINATES_FAILURE'

export const CLEAR_STORE = 'CLEAR_STORE'


